// birds-data.ts
// Pure data + types for the Bird Bingo page.

export type BirdInfo = {
  // Top-of-card meta
  scientificName?: string;
  order?: string;
  family?: string;
  groupName?: string; // e.g. "Rails", "Buntings"

  // Icon row
  habitat?: string; // "Lakes and ponds"
  food?: string; // "Plants"
  nesting?: string; // "Floating"
  behavior?: string; // "Surface dive"
  conservation?: string; // "Low concern"

  // Text blocks
  basicDescription?: string;
  songs?: string;
  calls?: string;
  otherSounds?: string;

  // Links
  sourceUrl?: string; // main Cornell species page
  lifeHistoryUrl?: string; // optional life history subpage
};

export type BirdSongVariant = {
  id: string;
  label: string;
  audio: string;
  note?: string;
};

export type Bird = {
  id: string;
  name: string;
  image?: string;
  imageMale?: string;
  imageFemale?: string;
  voice: string;
  call: string;
  info?: BirdInfo;
  variants?: BirdSongVariant[];
};

export const birds: Bird[] = [
  {
    id: "american-coot",
    name: "American Coot",
    imageMale: "/birds/img/american-coot-male.jpg",
    imageFemale: "/birds/img/american-coot-female.jpg",
    image: "/birds/img/american-coot.jpg",
    voice: "/birds/audio/american-coot-voice.mp3",
    call: "/birds/audio/american-coot-call.mp3",
    info: {
      // Top-of-card meta
      scientificName: "Fulica americana",
      order: "Gruiformes",
      family: "Rallidae",
      groupName: "Rails",

      // Icon row (from the Cornell-style card)
      habitat: "Lakes and ponds",
      food: "Plants",
      nesting: "Floating",
      behavior: "Surface dive",
      conservation: "Low concern",

      // Main blurb (paraphrased from Basic Description)
      basicDescription:
        "Stocky, dark waterbirds that cruise around open ponds and marshes with a stark white bill and forehead shield. They often forage alongside ducks, but a closer look at their slim head and long lobed toes reveals that coots are actually rails, more closely related to Sandhill Cranes and secretive marsh birds than to true ducks.",

      // Optional sound notes – you can tweak or delete if you prefer
      songs:
        "Gives series of short clucks, croaks, and grunts, often strung together into chattering, mechanical-sounding phrases.",
      calls:
        "Loud cackles, honks, and squawks used in contact, aggression, and alarm when squabbling on the water.",
      otherSounds:
        "Splashy, slapping footsteps as they run across the water during takeoff or fights, plus noisy wingbeats over the pond.",

      // Links back to Cornell
      sourceUrl: "https://www.allaboutbirds.org/guide/American_Coot",
      lifeHistoryUrl:
        "https://www.allaboutbirds.org/guide/American_Coot/lifehistory",
    },
    variants: [
      {
        id: "american-coot-classic-song",
        label: "Classic song",
        audio: "/birds/audio/american-coot-classic-song.mp3",
      },
      {
        id: "american-coot-pnw-dialect",
        label: "PNW dialect",
        audio: "/birds/audio/american-coot-pnw-dialect.mp3",
      },
    ],
  },
  {
    id: "american-crow",
    name: "American Crow",
    imageMale: "/birds/img/american-crow-male.jpg",
    imageFemale: "/birds/img/american-crow-female.jpg",
    image: "/birds/img/american-crow.jpg",
    voice: "/birds/audio/american-crow-voice.mp3",
    call: "/birds/audio/american-crow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-goldfinch",
    name: "American Goldfinch",
    imageMale: "/birds/img/american-goldfinch-male.jpg",
    imageFemale: "/birds/img/american-goldfinch-female.jpg",
    image: "/birds/img/american-goldfinch.jpg",
    voice: "/birds/audio/american-goldfinch-voice.mp3",
    call: "/birds/audio/american-goldfinch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-redstart",
    name: "American Redstart",
    imageMale: "/birds/img/american-redstart-male.jpg",
    imageFemale: "/birds/img/american-redstart-female.jpg",
    image: "/birds/img/american-redstart.jpg",
    voice: "/birds/audio/american-redstart-voice.mp3",
    call: "/birds/audio/american-redstart-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "american-robin",
    name: "American Robin",
    imageMale: "/birds/img/american-robin-male.jpg",
    imageFemale: "/birds/img/american-robin-female.jpg",
    image: "/birds/img/american-robin.jpg",
    voice: "/birds/audio/american-robin-voice.mp3",
    call: "/birds/audio/american-robin-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "bald-eagle",
    name: "Bald Eagle",
    imageMale: "/birds/img/bald-eagle-male.jpg",
    imageFemale: "/birds/img/bald-eagle-female.jpg",
    image: "/birds/img/bald-eagle.jpg",
    voice: "/birds/audio/bald-eagle-voice.mp3",
    call: "/birds/audio/bald-eagle-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "baltimore-oriole",
    name: "Baltimore Oriole",
    imageMale: "/birds/img/baltimore-oriole-male.jpg",
    imageFemale: "/birds/img/baltimore-oriole-female.jpg",
    image: "/birds/img/baltimore-oriole.jpg",
    voice: "/birds/audio/baltimore-oriole-voice.mp3",
    call: "/birds/audio/baltimore-oriole-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "belted-kingfisher",
    name: "Belted Kingfisher",
    imageMale: "/birds/img/belted-kingfisher-male.jpg",
    imageFemale: "/birds/img/belted-kingfisher-female.jpg",
    image: "/birds/img/belted-kingfisher.jpg",
    voice: "/birds/audio/belted-kingfisher-voice.mp3",
    call: "/birds/audio/belted-kingfisher-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "black-capped-chickadee",
    name: "Black-capped Chickadee",
    imageMale: "/birds/img/black-capped-chickadee-male.jpg",
    imageFemale: "/birds/img/black-capped-chickadee-female.jpg",
    image: "/birds/img/black-capped-chickadee.jpg",
    voice: "/birds/audio/black-capped-chickadee-voice.mp3",
    call: "/birds/audio/black-capped-chickadee-main.mp3",
    info: {
      // TODO: Cornell blurb if you want
    },
    variants: [
      {
        id: "bcc-fee-bee",
        label: "Fee-bee song",
        audio: "/birds/audio/black-capped-chickadee-fee-bee.mp3",
      },
      {
        id: "bcc-gargle",
        label: "Gargle call",
        audio: "/birds/audio/black-capped-chickadee-gargle.mp3",
      },
      {
        id: "bcc-high-see",
        label: "High see alarm",
        audio: "/birds/audio/black-capped-chickadee-high-see.mp3",
      },
    ],
  },
  {
    id: "black-phoebe",
    name: "Black Phoebe",
    imageMale: "/birds/img/black-phoebe-male.jpg",
    imageFemale: "/birds/img/black-phoebe-female.jpg",
    image: "/birds/img/black-phoebe.jpg",
    voice: "/birds/audio/black-phoebe-voice.mp3",
    call: "/birds/audio/black-phoebe-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "blue-jay",
    name: "Blue Jay",
    imageMale: "/birds/img/blue-jay-male.jpg",
    imageFemale: "/birds/img/blue-jay-female.jpg",
    image: "/birds/img/blue-jay.jpg",
    voice: "/birds/audio/blue-jay-voice.mp3",
    call: "/birds/audio/blue-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "brown-pelican",
    name: "Brown Pelican",
    imageMale: "/birds/img/brown-pelican-male.jpg",
    imageFemale: "/birds/img/brown-pelican-female.jpg",
    image: "/birds/img/brown-pelican.jpg",
    voice: "/birds/audio/brown-pelican-voice.mp3",
    call: "/birds/audio/brown-pelican-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "bufflehead",
    name: "Bufflehead",
    imageMale: "/birds/img/bufflehead-male.jpg",
    imageFemale: "/birds/img/bufflehead-female.jpg",
    image: "/birds/img/bufflehead.jpg",
    voice: "/birds/audio/bufflehead-voice.mp3",
    call: "/birds/audio/bufflehead-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "california-quail",
    name: "California Quail",
    imageMale: "/birds/img/california-quail-male.jpg",
    imageFemale: "/birds/img/california-quail-female.jpg",
    image: "/birds/img/california-quail.jpg",
    voice: "/birds/audio/california-quail-voice.mp3",
    call: "/birds/audio/california-quail-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "california-scrub-jay",
    name: "California Scrub-Jay",
    imageMale: "/birds/img/california-scrub-jay-male.jpg",
    imageFemale: "/birds/img/california-scrub-jay-female.jpg",
    image: "/birds/img/california-scrub-jay.jpg",
    voice: "/birds/audio/california-scrub-jay-voice.mp3",
    call: "/birds/audio/california-scrub-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "canada-goose",
    name: "Canada Goose",
    imageMale: "/birds/img/canada-goose-male.jpg",
    imageFemale: "/birds/img/canada-goose-female.jpg",
    image: "/birds/img/canada-goose.jpg",
    voice: "/birds/audio/canada-goose-voice.mp3",
    call: "/birds/audio/canada-goose-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "carolina-wren",
    name: "Carolina Wren",
    imageMale: "/birds/img/carolina-wren-male.jpg",
    imageFemale: "/birds/img/carolina-wren-female.jpg",
    image: "/birds/img/carolina-wren.jpg",
    voice: "/birds/audio/carolina-wren-voice.mp3",
    call: "/birds/audio/carolina-wren-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "cedar-waxwing",
    name: "Cedar Waxwing",
    imageMale: "/birds/img/cedar-waxwing-male.jpg",
    imageFemale: "/birds/img/cedar-waxwing-female.jpg",
    image: "/birds/img/cedar-waxwing.jpg",
    voice: "/birds/audio/cedar-waxwing-voice.mp3",
    call: "/birds/audio/cedar-waxwing-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "common-loon",
    name: "Common Loon",
    imageMale: "/birds/img/common-loon-male.jpg",
    imageFemale: "/birds/img/common-loon-female.jpg",
    image: "/birds/img/common-loon.jpg",
    voice: "/birds/audio/common-loon-voice.mp3",
    call: "/birds/audio/common-loon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "dark-eyed-junco",
    name: "Dark-Eyed Junco",
    imageMale: "/birds/img/dark-eyed-junco-male.jpg",
    imageFemale: "/birds/img/dark-eyed-junco-female.jpg",
    image: "/birds/img/dark-eyed-junco.jpg",
    voice: "/birds/audio/dark-eyed-junco-voice.mp3",
    call: "/birds/audio/dark-eyed-junco-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "double-crested-cormorant",
    name: "Double-crested Cormorant",
    imageMale: "/birds/img/double-crested-cormorant-male.jpg",
    imageFemale: "/birds/img/double-crested-cormorant-female.jpg",
    image: "/birds/img/double-crested-cormorant.jpg",
    voice: "/birds/audio/double-crested-cormorant-voice.mp3",
    call: "/birds/audio/double-crested-cormorant-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "eastern-bluebird",
    name: "Eastern Bluebird",
    imageMale: "/birds/img/eastern-bluebird-male.jpg",
    imageFemale: "/birds/img/eastern-bluebird-female.jpg",
    image: "/birds/img/eastern-bluebird.jpg",
    voice: "/birds/audio/eastern-bluebird-voice.mp3",
    call: "/birds/audio/eastern-bluebird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "great-blue-heron",
    name: "Great Blue Heron",
    imageMale: "/birds/img/great-blue-heron-male.jpg",
    imageFemale: "/birds/img/great-blue-heron-female.jpg",
    image: "/birds/img/great-blue-heron.jpg",
    voice: "/birds/audio/great-blue-heron-voice.mp3",
    call: "/birds/audio/great-blue-heron-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "great-horned-owl",
    name: "Great Horned Owl",
    imageMale: "/birds/img/great-horned-owl-male.jpg",
    imageFemale: "/birds/img/great-horned-owl-female.jpg",
    image: "/birds/img/great-horned-owl.jpg",
    voice: "/birds/audio/great-horned-owl-voice.mp3",
    call: "/birds/audio/great-horned-owl-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "house-finch",
    name: "House Finch",
    imageMale: "/birds/img/house-finch-male.jpg",
    imageFemale: "/birds/img/house-finch-female.jpg",
    image: "/birds/img/house-finch.jpg",
    voice: "/birds/audio/house-finch-voice.mp3",
    call: "/birds/audio/house-finch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "house-sparrow",
    name: "House Sparrow",
    imageMale: "/birds/img/house-sparrow-male.jpg",
    imageFemale: "/birds/img/house-sparrow-female.jpg",
    image: "/birds/img/house-sparrow.jpg",
    voice: "/birds/audio/house-sparrow-voice.mp3",
    call: "/birds/audio/house-sparrow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "indigo-bunting",
    name: "Indigo Bunting",
    imageMale: "/birds/img/indigo-bunting-male.jpg",
    imageFemale: "/birds/img/indigo-bunting-female.jpg",
    image: "/birds/img/indigo-bunting.jpg",
    voice: "/birds/audio/indigo-bunting-voice.mp3",
    call: "/birds/audio/indigo-bunting-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "killdeer",
    name: "Killdeer",
    imageMale: "/birds/img/killdeer-male.jpg",
    imageFemale: "/birds/img/killdeer-female.jpg",
    image: "/birds/img/killdeer.jpg",
    voice: "/birds/audio/killdeer-voice.mp3",
    call: "/birds/audio/killdeer-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "laughing-gull",
    name: "Laughing Gull",
    imageMale: "/birds/img/laughing-gull-male.jpg",
    imageFemale: "/birds/img/laughing-gull-female.jpg",
    image: "/birds/img/laughing-gull.jpg",
    voice: "/birds/audio/laughing-gull-voice.mp3",
    call: "/birds/audio/laughing-gull-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mallard",
    name: "Mallard",
    imageMale: "/birds/img/mallard-male.jpg",
    imageFemale: "/birds/img/mallard-female.jpg",
    image: "/birds/img/mallard.jpg",
    voice: "/birds/audio/mallard-voice.mp3",
    call: "/birds/audio/mallard-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mourning-dove",
    name: "Mourning Dove",
    imageMale: "/birds/img/mourning-dove-male.jpg",
    imageFemale: "/birds/img/mourning-dove-female.jpg",
    image: "/birds/img/mourning-dove.jpg",
    voice: "/birds/audio/mourning-dove-voice.mp3",
    call: "/birds/audio/mourning-dove-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "mute-swan",
    name: "Mute Swan",
    imageMale: "/birds/img/mute-swan-male.jpg",
    imageFemale: "/birds/img/mute-swan-female.jpg",
    image: "/birds/img/mute-swan.jpg",
    voice: "/birds/audio/mute-swan-voice.mp3",
    call: "/birds/audio/mute-swan-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-cardinal",
    name: "Northern Cardinal",
    imageMale: "/birds/img/northern-cardinal-male.jpg",
    imageFemale: "/birds/img/northern-cardinal-female.jpg",
    image: "/birds/img/northern-cardinal.jpg",
    voice: "/birds/audio/northern-cardinal-voice.mp3",
    call: "/birds/audio/northern-cardinal-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-flicker",
    name: "Northern Flicker",
    imageMale: "/birds/img/northern-flicker-male.jpg",
    imageFemale: "/birds/img/northern-flicker-female.jpg",
    image: "/birds/img/northern-flicker.jpg",
    voice: "/birds/audio/northern-flicker-voice.mp3",
    call: "/birds/audio/northern-flicker-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "northern-mockingbird",
    name: "Northern Mockingbird",
    imageMale: "/birds/img/northern-mockingbird-male.jpg",
    imageFemale: "/birds/img/northern-mockingbird-female.jpg",
    image: "/birds/img/northern-mockingbird.jpg",
    voice: "/birds/audio/northern-mockingbird-voice.mp3",
    call: "/birds/audio/northern-mockingbird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "pileated-woodpecker",
    name: "Pileated Woodpecker",
    imageMale: "/birds/img/pileated-woodpecker-male.jpg",
    imageFemale: "/birds/img/pileated-woodpecker-female.jpg",
    image: "/birds/img/pileated-woodpecker.jpg",
    voice: "/birds/audio/pileated-woodpecker-voice.mp3",
    call: "/birds/audio/pileated-woodpecker-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "red-tailed-hawk",
    name: "Red-Tailed Hawk",
    imageMale: "/birds/img/red-tailed-hawk-male.jpg",
    imageFemale: "/birds/img/red-tailed-hawk-female.jpg",
    image: "/birds/img/red-tailed-hawk.jpg",
    voice: "/birds/audio/red-tailed-hawk-voice.mp3",
    call: "/birds/audio/red-tailed-hawk-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "ring-billed-gull",
    name: "Ring-Billed Gull",
    imageMale: "/birds/img/ring-billed-gull-male.jpg",
    imageFemale: "/birds/img/ring-billed-gull-female.jpg",
    image: "/birds/img/ring-billed-gull.jpg",
    voice: "/birds/audio/ring-billed-gull-voice.mp3",
    call: "/birds/audio/ring-billed-gull-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "rock-pigeon",
    name: "Rock Pigeon",
    imageMale: "/birds/img/rock-pigeon-male.jpg",
    imageFemale: "/birds/img/rock-pigeon-female.jpg",
    image: "/birds/img/rock-pigeon.jpg",
    voice: "/birds/audio/rock-pigeon-voice.mp3",
    call: "/birds/audio/rock-pigeon-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "rose-breasted-grosbeak",
    name: "Rose-breasted Grosbeak",
    imageMale: "/birds/img/rose-breasted-grosbeak-male.jpg",
    imageFemale: "/birds/img/rose-breasted-grosbeak-female.jpg",
    image: "/birds/img/rose-breasted-grosbeak.jpg",
    voice: "/birds/audio/rose-breasted-grosbeak-voice.mp3",
    call: "/birds/audio/rose-breasted-grosbeak-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "ruby-throated-hummingbird",
    name: "Ruby Throated Hummingbird",
    imageMale: "/birds/img/ruby-throated-hummingbird-male.jpg",
    imageFemale: "/birds/img/ruby-throated-hummingbird-female.jpg",
    image: "/birds/img/ruby-throated-hummingbird.jpg",
    voice: "/birds/audio/ruby-throated-hummingbird-voice.mp3",
    call: "/birds/audio/ruby-throated-hummingbird-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "sandhill-crane",
    name: "Sandhill Crane",
    imageMale: "/birds/img/sandhill-crane-male.jpg",
    imageFemale: "/birds/img/sandhill-crane-female.jpg",
    image: "/birds/img/sandhill-crane.jpg",
    voice: "/birds/audio/sandhill-crane-voice.mp3",
    call: "/birds/audio/sandhill-crane-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "scarlet-tanager",
    name: "Scarlet Tanager",
    imageMale: "/birds/img/scarlet-tanager-male.jpg",
    imageFemale: "/birds/img/scarlet-tanager-female.jpg",
    image: "/birds/img/scarlet-tanager.jpg",
    voice: "/birds/audio/scarlet-tanager-voice.mp3",
    call: "/birds/audio/scarlet-tanager-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "spotted-towhee",
    name: "Spotted Towhee",
    imageMale: "/birds/img/spotted-towhee-male.jpg",
    imageFemale: "/birds/img/spotted-towhee-female.jpg",
    image: "/birds/img/spotted-towhee.jpg",
    voice: "/birds/audio/spotted-towhee-voice.mp3",
    call: "/birds/audio/spotted-towhee-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "stellers-jay",
    name: "Steller's Jay",
    imageMale: "/birds/img/stellers-jay-male.jpg",
    imageFemale: "/birds/img/stellers-jay-female.jpg",
    image: "/birds/img/stellers-jay.jpg",
    voice: "/birds/audio/stellers-jay-voice.mp3",
    call: "/birds/audio/stellers-jay-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "swainsons-thrush",
    name: "Swainson's Thrush",
    imageMale: "/birds/img/swainsons-thrush-male.jpg",
    imageFemale: "/birds/img/swainsons-thrush-female.jpg",
    image: "/birds/img/swainsons-thrush.jpg",
    voice: "/birds/audio/swainsons-thrush-voice.mp3",
    call: "/birds/audio/swainsons-thrush-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "tree-swallow",
    name: "Tree Swallow",
    imageMale: "/birds/img/tree-swallow-male.jpg",
    imageFemale: "/birds/img/tree-swallow-female.jpg",
    image: "/birds/img/tree-swallow.jpg",
    voice: "/birds/audio/tree-swallow-voice.mp3",
    call: "/birds/audio/tree-swallow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "tufted-titmouse",
    name: "Tufted Titmouse",
    imageMale: "/birds/img/tufted-titmouse-male.jpg",
    imageFemale: "/birds/img/tufted-titmouse-female.jpg",
    image: "/birds/img/tufted-titmouse.jpg",
    voice: "/birds/audio/tufted-titmouse-voice.mp3",
    call: "/birds/audio/tufted-titmouse-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "western-meadowlark",
    name: "Western Meadowlark",
    imageMale: "/birds/img/western-meadowlark-male.jpg",
    imageFemale: "/birds/img/western-meadowlark-female.jpg",
    image: "/birds/img/western-meadowlark.jpg",
    voice: "/birds/audio/western-meadowlark-voice.mp3",
    call: "/birds/audio/western-meadowlark-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "western-tanager",
    name: "Western Tanager",
    imageMale: "/birds/img/western-tanager-male.jpg",
    imageFemale: "/birds/img/western-tanager-female.jpg",
    image: "/birds/img/western-tanager.jpg",
    voice: "/birds/audio/western-tanager-voice.mp3",
    call: "/birds/audio/western-tanager-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "white-breasted-nuthatch",
    name: "White-Breasted Nuthatch",
    imageMale: "/birds/img/white-breasted-nuthatch-male.jpg",
    imageFemale: "/birds/img/white-breasted-nuthatch-female.jpg",
    image: "/birds/img/white-breasted-nuthatch.jpg",
    voice: "/birds/audio/white-breasted-nuthatch-voice.mp3",
    call: "/birds/audio/white-breasted-nuthatch-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "white-throated-sparrow",
    name: "White-Throated Sparrow",
    imageMale: "/birds/img/white-throated-sparrow-male.jpg",
    imageFemale: "/birds/img/white-throated-sparrow-female.jpg",
    image: "/birds/img/white-throated-sparrow.jpg",
    voice: "/birds/audio/white-throated-sparrow-voice.mp3",
    call: "/birds/audio/white-throated-sparrow-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "wood-duck",
    name: "Wood Duck",
    imageMale: "/birds/img/wood-duck-male.jpg",
    imageFemale: "/birds/img/wood-duck-female.jpg",
    image: "/birds/img/wood-duck.jpg",
    voice: "/birds/audio/wood-duck-voice.mp3",
    call: "/birds/audio/wood-duck-call.mp3",
    info: { songs: "" },
    variants: [],
  },
  {
    id: "yellow-rumped-warbler",
    name: "Yellow-Rumped Warbler",
    imageMale: "/birds/img/yellow-rumped-warbler-male.jpg",
    imageFemale: "/birds/img/yellow-rumped-warbler-female.jpg",
    image: "/birds/img/yellow-rumped-warbler.jpg",
    voice: "/birds/audio/yellow-rumped-warbler-voice.mp3",
    call: "/birds/audio/yellow-rumped-warbler-call.mp3",
    info: { songs: "" },
    variants: [],
  },
];
